#!/bin/sh
get() {
    name=$(ibus engine)
    case "$name" in
        xkb:us::eng)
            echo "en"
            ;;

        mozc-jp)
            echo "jp"
            ;;
    esac
}

case "$1" in
    get)
        name=$(get)
        [ "$name" = "en" ] && echo "🍔" || echo "🍙"
        ;;

    toggle)
        name=$(get)
        if [ "$name" = "en" ]; then
            ibus engine mozc-jp
            notify-send "Keyboard Layout: jp"
            pkill -RTMIN+11 dwmblocks
        else
            ibus engine xkb:us::eng
            notify-send "Keyboard Layout: en"
            pkill -RTMIN+11 dwmblocks
        fi

esac
