#!/bin/sh
set_kb() {
    ibus engine "$1"
    notify-send -h string:x-canonical-private-synchronous:kb "Keyboard: $(ibus engine)"
    pkill -RTMIN+11 dwmblocks
}

case "$1" in
    get)
        ibus engine
        ;;

    set)
        set_kb $(ibus list-engine | rofi -dmenu -p 'Select engine')
        ;;

    toggle)
        name=$(ibus engine)
        if [ "$name" = "xkb:us::eng" ]; then
            set_kb mozc-jp
        else
            set_kb xkb:us::eng
        fi
        ;;

esac
