#!/bin/sh
# if file was given, use that file
[ -f "$1" ] && bg=$1

# if directory was given, choose one file randomly
[ -d "$1" ] && bg=$(find $1 -name "*.png" -o -name "*.jpg" | shuf -n 1)

if [ -n "$bg" ]; then
    xwallpaper --zoom $bg
    notify-send -h string:x-canonical-private-synchronous:bg "Set background to $bg"
else
    echo "Wallpaper '$bg' not found."
    exit 1
fi
